const {sectors,missions,allMissions}=window.StarcodeData;
const $=id=>document.getElementById(id);
const KEY='starcode-bai10-save-v1',PASSWORD='05067379'; // Mã giao diện trong web tĩnh, không phải cơ chế bảo mật.
const accents=['#7cecff','#b89dff','#ffd187','#79efc9','#ff9aca','#fff0a6'];
const routes=[
 [[12,76],[31,65],[45,40],[67,37],[85,17]],[[12,78],[25,51],[49,60],[69,32],[86,15]],
 [[12,79],[27,63],[48,42],[69,52],[87,16]],[[11,74],[30,43],[49,58],[68,28],[88,17]],
 [[13,78],[30,58],[48,33],[66,51],[85,16]],[[11,77],[39,58],[63,35],[88,15]]
];
const fresh=()=>({name:'Phi công',unlocked:0,completed:[],score:0,hints:3,sector:0,index:0,lives:3,streak:0,freezeUsed:false,timeLeft:60,soundOn:true,volume:65});
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&typeof s==='object')return {...fresh(),name:String(s.name||'Phi công').slice(0,18),unlocked:Math.min(5,Math.max(0,Number(s.unlocked)||0)),completed:Array.isArray(s.completed)?s.completed.filter(i=>Number.isInteger(i)&&i>=0&&i<=5):[],score:Math.max(0,Number(s.score)||0),hints:Math.min(3,Math.max(0,Number(s.hints)||0)),sector:Math.min(5,Math.max(0,Number(s.sector)||0)),index:Math.max(0,Number(s.index)||0),lives:Math.min(3,Math.max(0,Number(s.lives)||0)),streak:Math.max(0,Number(s.streak)||0),freezeUsed:!!s.freezeUsed,timeLeft:Math.min(60,Math.max(1,Number(s.timeLeft)||60)),soundOn:s.soundOn!==false,volume:Number.isFinite(Number(s.volume))?Math.min(100,Math.max(0,Number(s.volume))):65}}catch{}return fresh()}
let state=load(),view='home',picked=[],wrongLine=null,fixId=null,remain=60,deadline=0,freezeUntil=0,timer=null,music=null,musicTick=0,audioCtx=null,busy=false,dialogClose=null,teacherIndex=0,hiddenAt=0,teacherTest=false,studentSnapshot=null,studentReturnView='map',studentDraft=null,flightToken=0;
const persist=()=>{if(teacherTest)return;try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const nfmt=n=>String(n).replace('-', '−').replace('.',',');
// Chuyển những biểu thức ∛ trong lời giải và lệnh thành dấu căn có gạch phủ đầy đủ.
function typesetRoots(html){
 const template=document.createElement('template');template.innerHTML=html;
 const walker=document.createTreeWalker(template.content,NodeFilter.SHOW_TEXT);
 const nodes=[];while(walker.nextNode())if(walker.currentNode.textContent.includes('∛'))nodes.push(walker.currentNode);
 for(const node of nodes){
  const value=node.textContent;let offset=0;const replacement=document.createDocumentFragment();
  while(offset<value.length){
   const start=value.indexOf('∛',offset);if(start<0){replacement.append(document.createTextNode(value.slice(offset)));break}
   replacement.append(document.createTextNode(value.slice(offset,start)));
   let end=start+1,radicand='';
   if(value[end]==='('){const open=end;let depth=1;end++;while(end<value.length&&depth){if(value[end]==='(')depth++;else if(value[end]===')')depth--;if(depth)radicand+=value[end];end++}if(depth){end=open;radicand=''}}
   if(!radicand){const match=value.slice(end).match(/^[−-]?(?:\d+(?: \d{3})*(?:[.,]\d+)?|[A-Za-z]+(?:³)?)/);if(match){radicand=match[0];end+=match[0].length}}
   if(!radicand){replacement.append(document.createTextNode('∛'));offset=start+1;continue}
   const fractionMatch=radicand.match(/^([−-]?\d+)\/(\d+)$/);
   const safe=esc(radicand);const body=fractionMatch?window.StarcodeData.fraction(esc(fractionMatch[1]),esc(fractionMatch[2])):safe;
   const math=document.createElement('template');math.innerHTML=window.StarcodeData.root(body,radicand);replacement.append(math.content);offset=end;
  }
  node.replaceWith(replacement);
 }
 return template.innerHTML;
}
function setView(name){if(view==='game'&&name!=='game'&&!busy&&state.index<missions[state.sector].length&&state.lives>0){state.timeLeft=remain;persist()}view=name;for(const x of ['home','map','game'])$(x+'View').classList.toggle('hidden',x!==name);$('homeStrip').classList.toggle('hidden',name!=='home');$('topProgress').textContent=`HÀNH TRÌNH ${String(state.completed.length).padStart(2,'0')} / 06`;if(name==='map')renderMap();if(name!=='game'){stopClock();stopMusic()}window.scrollTo({top:0,behavior:'instant'})}
function audio(){try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch{return null}}
function tone(freq,duration=.12,type='triangle',volume=.045,delay=0){if(!state.soundOn||state.volume<=0)return;const ctx=audio();if(!ctx)return;const osc=ctx.createOscillator(),gain=ctx.createGain(),at=ctx.currentTime+delay;osc.type=type;osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(Math.max(.0002,volume*state.volume/65),at+.012);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);osc.connect(gain).connect(ctx.destination);osc.start(at);osc.stop(at+duration+.02)}
const sfx={click:()=>tone(520,.05,'sine',.025),correct:()=>{tone(440,.1,'triangle',.06);tone(659,.17,'sine',.06,.12);tone(880,.22,'sine',.04,.24)},wrong:()=>{tone(150,.15,'sawtooth',.03);tone(110,.18,'triangle',.032,.1)},complete:()=>[392,494,587,784].forEach((f,i)=>tone(f,.22,'triangle',.055,i*.14))};
function stopMusic(){if(music){clearInterval(music);music=null}}
const soundscapes=[{pace:350,wave:'triangle',bass:'sine',pattern:[0,1,2,3,2,1,3,0],spark:2},{pace:420,wave:'sine',bass:'triangle',pattern:[0,2,1,3,0,3,1,2],spark:3},{pace:285,wave:'triangle',bass:'sine',pattern:[3,2,1,0,1,3,2,0],spark:4},{pace:390,wave:'square',bass:'sine',pattern:[0,0,2,1,3,1,2,3],spark:2},{pace:315,wave:'sawtooth',bass:'triangle',pattern:[0,3,1,2,3,1,0,2],spark:4},{pace:255,wave:'sine',bass:'triangle',pattern:[0,1,2,3,2,3,1,0],spark:2}];
function startMusic(){stopMusic();if(!state.soundOn||state.volume<=0||view!=='game')return;musicTick=0;const profile=soundscapes[state.sector];const beat=()=>{if(document.hidden||view!=='game')return;const tune=sectors[state.sector].music,n=tune[profile.pattern[musicTick%profile.pattern.length]%tune.length];tone(n,profile.pace/1000*.72,profile.wave,state.sector===3?.009:.015);if(musicTick%profile.spark===0)tone(n*2,.12,'sine',.006,.07);if(musicTick%4===0)tone(tune[0]/2,.48,profile.bass,.015);musicTick++};beat();music=setInterval(beat,profile.pace)}
function soundUI(){$('soundBtn').textContent=state.soundOn&&state.volume>0?'♫':'♪̸';$('soundBtn').setAttribute('aria-pressed',String(state.soundOn));$('volumeRange').value=state.volume;$('volumeValue').textContent=`${state.volume}%`;$('volumeBtn').textContent=state.volume===0?'◖̸':state.volume<35?'◖':'◕'}
function showWarp(i){const overlay=$('warpOverlay');$('warpName').textContent=sectors[i].name.toUpperCase();overlay.classList.remove('hidden','warp-fade');void overlay.offsetWidth;overlay.classList.add('warp-active');setTimeout(()=>{overlay.classList.add('warp-fade');setTimeout(()=>{overlay.classList.add('hidden');overlay.classList.remove('warp-active','warp-fade')},380)},780)}
function refreshTeacherTestUI(){$('teacherTestBadge').classList.toggle('hidden',!teacherTest);$('exitTestBtn').classList.toggle('hidden',!teacherTest);$('backBtn').classList.toggle('hidden',teacherTest)}

function renderMap(){$('mapWelcome').textContent=`Phi công ${state.name} · Khu vực tiếp theo mở sau khi hoàn thành khu trước.`;$('mapScore').textContent=String(state.score).padStart(4,'0');const grid=$('mapGrid');grid.replaceChildren();sectors.forEach((s,i)=>{const done=state.completed.includes(i),locked=i>state.unlocked&&!done,card=document.createElement('button');card.type='button';card.className='map-card';card.style.setProperty('--card-color',accents[i]);card.style.setProperty('--card-delay',`${i*85}ms`);card.disabled=locked;card.innerHTML=`<div class="card-top"><span>VÙNG ${String(i+1).padStart(2,'0')} / 06</span><span class="status-pill">${locked?'◌ KHÓA':done?'✓ HOÀN TẤT':'● SẴN SÀNG'}</span></div><span class="planet-icon" aria-hidden="true"></span><h3>${s.name}</h3><p>${s.description}</p><div class="card-bottom"><span>${s.tag.toUpperCase()}</span><span>${locked?'⌑':'↗'}</span></div>`;if(!locked)card.addEventListener('click',()=>enterSector(i));grid.append(card)})}
function enterSector(i){if(i>state.unlocked&&!state.completed.includes(i))return;const resume=i===state.sector&&state.index<missions[i].length&&state.lives>0&&!state.completed.includes(i);if(!resume){state.sector=i;state.index=0;state.lives=3;state.hints=3;state.streak=0;state.freezeUsed=false;state.timeLeft=60}else state.sector=i;persist();setView('game');renderMission();startMusic();showWarp(i)}
function beginTeacherTest(i){studentReturnView=view;studentSnapshot=structuredClone(state);studentDraft=view==='game'?{picked:[...picked],wrongLine,fixId,answer:$('answerInput')?.value??'',remain,busy}:null;if(view==='game'&&!busy&&state.lives>0){studentSnapshot.timeLeft=remain;try{localStorage.setItem(KEY,JSON.stringify(studentSnapshot))}catch{}}flightToken++;stopClock();stopMusic();closeDialog(false);teacherTest=true;state={...fresh(),name:'Giáo viên',sector:i,soundOn:studentSnapshot.soundOn,volume:studentSnapshot.volume};setView('game');refreshTeacherTestUI();renderMission();startMusic();showWarp(i)}
function endTeacherTest(){if(!teacherTest)return;flightToken++;stopClock();stopMusic();closeDialog(false);teacherTest=false;state=studentSnapshot;studentSnapshot=null;const destination=studentReturnView;const draft=studentDraft;studentDraft=null;view='restore';setView(destination);refreshTeacherTestUI();soundUI();if(destination==='game'&&state.index<missions[state.sector].length&&state.lives>0){renderMission();if(draft){picked=[...draft.picked];wrongLine=draft.wrongLine;fixId=draft.fixId;renderEditor();if($('answerInput'))$('answerInput').value=draft.answer;remain=draft.remain;state.timeLeft=remain;resumeClock();if(draft.busy){busy=true;stopClock();feedback('Tiếp tục hành trình từ nhiệm vụ hiện tại.')}}startMusic()}teacherPanel()}
function stopClock(){if(timer){clearInterval(timer);timer=null}}
function startClock(){stopClock();remain=state.timeLeft;freezeUntil=0;deadline=performance.now()+remain*1000;showClock();timer=setInterval(tickClock,160)}
function resumeClock(){stopClock();deadline=performance.now()+remain*1000;freezeUntil=0;showClock();timer=setInterval(tickClock,160)}
function showClock(){$('timeText').textContent=`${String(Math.floor(remain/60)).padStart(2,'0')}:${String(remain%60).padStart(2,'0')}`;$('timeFill').style.width=`${remain/60*100}%`;$('timeText').parentElement.classList.toggle('urgent',remain<=10)}
function tickClock(){if(view!=='game'||busy||document.hidden)return;const now=performance.now();if(freezeUntil&&now<freezeUntil)return;const previous=remain;remain=Math.max(0,Math.ceil((deadline-now)/1000));showClock();if(remain!==previous&&remain>0){state.timeLeft=remain;persist()}if(remain===0){stopClock();loseLife('Hết 60 giây. Chạy lại nhiệm vụ này.',true)}}
document.addEventListener('visibilitychange',()=>{if(document.hidden)hiddenAt=performance.now();else if(hiddenAt){deadline+=performance.now()-hiddenAt;hiddenAt=0}});
function updateHud(){const len=missions[state.sector].length;$('lifeText').textContent='♥ '.repeat(state.lives).trim()+' ♡'.repeat(3-state.lives);$('lifeText').setAttribute('aria-label',`${state.lives} mạng`);$('missionCount').textContent=`${String(Math.min(state.index+1,len)).padStart(2,'0')} / ${String(len).padStart(2,'0')}`;$('gameScore').textContent=String(state.score).padStart(4,'0');$('hintCount').textContent=String(state.hints).padStart(2,'0');$('hintBadge').textContent=state.hints;$('hintBtn').disabled=state.hints===0;$('freezeBtn').disabled=state.freezeUsed;$('freezeBtn').textContent=state.freezeUsed?'◷ ĐÃ DÙNG':'◷ DỪNG 10s'}
function routePath(points){return points.map((p,i)=>`${i?'L':'M'} ${p[0]*5.6} ${p[1]*4}`).join(' ')}
function drawRoute(position=state.index){const points=routes[state.sector],length=missions[state.sector].length,idx=Math.min(position,length);$('routeShadow').setAttribute('d',routePath(points));$('routeProgress').setAttribute('d',routePath(points.slice(0,idx+1)));$('routeNodes').innerHTML=points.map((p,i)=>`<circle cx="${p[0]*5.6}" cy="${p[1]*4}" r="${i<=idx?7:5}" fill="${i<=idx?accents[state.sector]:'#355674'}" stroke="#d9ffff" stroke-opacity="${i<=idx?.9:.3}" stroke-width="2"/>`).join('');const point=points[idx];const next=points[Math.min(idx+1,length)],dx=next[0]-point[0],dy=next[1]-point[1],deg=Math.atan2(dy,dx)*180/Math.PI+90;const ship=$('shipMarker');ship.style.left=point[0]+'%';ship.style.top=point[1]+'%';ship.style.transform=`translate(-50%,-50%) rotate(${deg}deg)`;const aura=$('shipAura');aura.style.left=point[0]+'%';aura.style.top=point[1]+'%';const burst=$('warpBurst');burst.style.left=point[0]+'%';burst.style.top=point[1]+'%';$('routeNumber').textContent=`${String(Math.min(idx+1,length)).padStart(2,'0')} — ${String(length).padStart(2,'0')}`;$('flightPips').innerHTML=Array.from({length},(_,i)=>`<i class="${i<idx?'done':i===idx?'current':''}"></i>`).join('')}
function feedback(text='',kind=''){$('feedback').innerHTML=typesetRoots(esc(text));$('feedback').className=`feedback ${text?'show':''} ${kind}`}
function renderMission(){busy=false;picked=[];wrongLine=null;fixId=null;const i=state.sector,q=missions[i][state.index],s=sectors[i];document.body.dataset.sector=i;document.documentElement.style.setProperty('--accent',accents[i]);$('regionCode').textContent=`VÙNG ${String(i+1).padStart(2,'0')} / 06 · ${i===5?'CỔNG SAO':'QUỸ ĐẠO'}`;$('regionName').textContent=s.name.toUpperCase();$('regionTag').textContent=s.tag.toUpperCase();$('flightCode').textContent=`SC—${String(i+1).padStart(2,'0')}`;$('missionId').textContent=`NHIỆM VỤ ${q.id}`;$('missionMode').textContent={program:'XẾP LỆNH',input:'ĐIỀN THAM SỐ',debug:'SỬA LỆNH'}[q.mode];$('missionTitle').textContent=q.title;$('missionSignal').innerHTML=q.signal;$('missionSignal').classList.toggle('long',q.signal.length>190);$('missionPrompt').textContent=q.prompt;$('shipState').textContent='● ĐANG CHỜ LỆNH';$('flightLog').textContent='NAV // Tọa độ sẵn sàng';$('guideLine').textContent=q.mode==='program'?'NOVA // Chạm lệnh theo thứ tự, hoặc kéo vào từng ô.':q.mode==='debug'?'NOVA // Chọn dòng sai và lệnh thay thế.':'NOVA // Nhập số để chạy môđun.';$('executeBtn').disabled=false;feedback();drawRoute();updateHud();renderEditor();startClock()}
function renderEditor(){const q=missions[state.sector][state.index],box=$('editor');box.replaceChildren();if(q.mode==='program')renderProgram(q,box);if(q.mode==='debug')renderDebug(q,box);if(q.mode==='input')renderInput(box)}
function renderProgram(q,box){box.innerHTML='<div class="editor-title">THỨ TỰ THỰC THI · CHẠM Ô ĐÃ ĐIỀN ĐỂ XÓA</div><div class="command-slots" id="slots"></div><div class="editor-title">BỘ LỆNH · CHẠM HOẶC KÉO THẢ</div><div class="command-pool" id="pool"></div>';q.order.forEach((_,i)=>{const b=document.createElement('button');b.type='button';b.className=`slot ${picked[i]?'filled':''}`;b.innerHTML=`<b>${String(i+1).padStart(2,'0')}</b><span>${picked[i]?typesetRoots(q.pool.find(x=>x.id===picked[i]).text):'Thả lệnh vào đây'}</span>`;b.setAttribute('aria-label',picked[i]?`Lệnh ${i+1}: ${b.textContent}. Chạm để xóa`:`Ô lệnh ${i+1}`);b.addEventListener('click',()=>{if(i<picked.length){picked.splice(i,1);renderEditor();sfx.click()}});b.addEventListener('dragover',e=>e.preventDefault());b.addEventListener('drop',e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(q.pool.some(c=>c.id===id)){picked=picked.filter(x=>x!==id);picked.splice(Math.min(i,picked.length),0,id);picked=picked.slice(0,3);renderEditor();sfx.click()}});$('slots').append(b)});q.pool.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.className=`command ${picked.includes(c.id)?'used':''}`;b.disabled=picked.includes(c.id);b.draggable=true;b.innerHTML=`<span class="command-num">${i+1}</span>${typesetRoots(c.text)}`;b.addEventListener('click',()=>{if(picked.length<3){picked.push(c.id);renderEditor();sfx.click()}else feedback('Ba ô lệnh đã đầy. Chạm một ô để bỏ lệnh rồi chọn lại.')} );b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',c.id));$('pool').append(b)})}
function renderDebug(q,box){box.innerHTML='<div class="editor-title">CHỌN DÒNG CÓ LỖI</div><div class="debug-lines" id="debugLines"></div><div class="editor-title">CHỌN LỆNH THAY THẾ</div><div class="fix-list" id="fixList"></div>';q.lines.forEach((line,i)=>{const b=document.createElement('button');b.type='button';b.className=`debug-line ${wrongLine===i?'selected':''}`;b.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span>${typesetRoots(line)}`;b.setAttribute('aria-pressed',String(wrongLine===i));b.addEventListener('click',()=>{wrongLine=i;renderEditor();sfx.click()});$('debugLines').append(b)});q.fixes.forEach(f=>{const b=document.createElement('button');b.type='button';b.className=`fix-option ${fixId===f.id?'selected':''}`;b.innerHTML=typesetRoots(f.text);b.setAttribute('aria-pressed',String(fixId===f.id));b.addEventListener('click',()=>{fixId=f.id;renderEditor();sfx.click()});$('fixList').append(b)})}
function renderInput(box){box.innerHTML='<div class="editor-title">THAM SỐ ĐẦU RA</div><input id="answerInput" class="terminal-input" type="text" inputmode="decimal" autocomplete="off" spellcheck="false" placeholder="Ví dụ: −2,5" aria-label="Nhập kết quả"><div id="keypad" class="keypad" aria-label="Bàn phím số"></div>';$('answerInput').addEventListener('keydown',e=>{if(e.key==='Enter')execute()});for(const key of ['1','2','3','4','5','6','7','8','9','−','0',',','⌫','XÓA']){const b=document.createElement('button');b.type='button';b.textContent=key;b.addEventListener('click',()=>{const target=$('answerInput');if(key==='XÓA')target.value='';else if(key==='⌫')target.value=target.value.slice(0,-1);else target.value+=key;target.focus();sfx.click()});$('keypad').append(b)}}
function parseNumber(raw){const str=String(raw).trim().replace(/[−–]/g,'-').replace(/\s/g,'').replace(',','.');if(!/^[-+]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(str))return null;const v=Number(str);return Number.isFinite(v)?v:null}
function execute(){if(view!=='game'||busy)return;const q=missions[state.sector][state.index];let correct=false,message='';if(q.mode==='program'){
 if(picked.length<3){feedback('Hãy điền đủ ba ô lệnh trước khi chạy.','bad');return}
 correct=q.order.every((id,i)=>picked[i]===id);if(!correct){const wrongAt=q.order.findIndex((id,i)=>picked[i]!==id);message=`Lệnh ${wrongAt+1} làm lệch quỹ đạo. Xem lại thứ tự các bước tính.`}
 }else if(q.mode==='debug'){
 if(wrongLine===null||fixId===null){feedback('Hãy chọn cả dòng lỗi và lệnh thay thế.','bad');return}
 correct=wrongLine===q.fault&&fixId===q.fix;message=wrongLine!==q.fault?'Dòng đã chọn chưa phải chỗ sai. Kiểm tra từng đẳng thức.':'Đã tìm đúng dòng lỗi, nhưng lệnh thay thế còn sai.';
 }else{const value=parseNumber($('answerInput').value);if(value===null){feedback('Nhập một số hợp lệ; có thể dùng dấu − và dấu phẩy thập phân.','bad');$('answerInput').focus();return}correct=Math.abs(value-q.answer)<1e-8;message='Tham số chưa đúng. Kiểm tra lập phương, dấu và phép làm tròn.'}
 if(correct){busy=true;stopClock();sfx.correct();state.score+=100+remain*2;state.streak++;let bonus='';if(state.streak%2===0&&state.hints<3){state.hints++;bonus=' · +1 gợi ý'}state.index++;state.timeLeft=60;const last=state.index>=missions[state.sector].length;if(last&&!state.completed.includes(state.sector)){state.completed.push(state.sector);state.unlocked=Math.min(5,Math.max(state.unlocked,state.sector+1))}persist();$('gameScore').textContent=String(state.score).padStart(4,'0');$('hintCount').textContent=String(state.hints).padStart(2,'0');$('hintBadge').textContent=state.hints;feedback(`Lệnh hợp lệ! ${q.explain}${bonus}`);$('shipState').textContent='● BAY ĐÚNG QUỸ ĐẠO';$('flightLog').textContent='NAV // Lệnh được thực thi';$('executeBtn').disabled=true;$('editor').querySelectorAll('button,input').forEach(n=>n.disabled=true);drawRoute(state.index);const burst=$('warpBurst');burst.classList.remove('burst-on');void burst.offsetWidth;burst.classList.add('burst-on');const token=flightToken;setTimeout(()=>{if(view!=='game'||token!==flightToken)return;if(last)sectorWon();else renderMission()},1650);
 }else{loseLife(message,false)}}
function loseLife(message,timedOut){sfx.wrong();state.lives=Math.max(0,state.lives-1);state.streak=0;if(timedOut)state.timeLeft=60;persist();updateHud();feedback(`${message} Mất 1 mạng.`,'bad');$('shipState').textContent='● CẦN SỬA LỆNH';$('flightLog').textContent='NAV // Lỗi thuật toán';const ship=$('shipMarker');ship.classList.remove('wobble');void ship.offsetWidth;ship.classList.add('wobble');$('courseGlitch').classList.add('show');setTimeout(()=>$('courseGlitch').classList.remove('show'),600);if(state.lives===0){stopClock();const token=flightToken;setTimeout(()=>{if(token===flightToken)gameOver()},800)}else if(timedOut){remain=60;deadline=performance.now()+60000;showClock();timer=setInterval(tickClock,160)}}
function sectorWon(){stopClock();sfx.complete();if(teacherTest){openDialog(`<div class="small-label">THỬ MÀN GIÁO VIÊN</div><div class="win-mark">✧</div><h2 id="dialogTitle">MÀN CHẠY ỔN!</h2><p>Đã hoàn thành mọi nhiệm vụ ở ${sectors[state.sector].name}. Kết quả thử không thay đổi tiến độ học sinh.</p><div class="dialog-actions"><button type="button" class="primary-btn" data-action="retry">THỬ LẠI ↗</button><button type="button" class="back-btn" data-action="teacher-return">VỀ GIÁO VIÊN</button></div>`,endTeacherTest);return}const last=state.sector===5;openDialog(`<div class="small-label">${last?'HỆ THỐNG BẢN ĐỒ ĐÃ SÁNG':'ĐÃ HOÀN THÀNH VÙNG BAY'}</div><div class="win-mark">✧</div><h2 id="dialogTitle">${last?'VỀ ĐÍCH THÀNH CÔNG!':'QUỸ ĐẠO ĐÃ MỞ'}</h2><p>${last?'Bạn đã giải xong cả sáu vùng không gian.':`Phi công ${esc(state.name)} đã dẫn phi thuyền qua ${sectors[state.sector].name}. Vùng tiếp theo đã mở.`}</p><div class="result-row"><span>ĐIỂM: ${state.score}</span><span>CÒN ${state.lives}/3 MẠNG</span><span>${state.completed.length}/6 VÙNG</span></div><div class="dialog-actions"><button type="button" class="primary-btn" data-action="map">XEM BẢN ĐỒ ↗</button><button type="button" class="back-btn" data-action="retry">CHƠI LẠI VÙNG</button></div>`,()=>setView('map'))}
function gameOver(){if(view!=='game'||state.lives>0)return;if(teacherTest){openDialog('<div class="small-label">THỬ MÀN GIÁO VIÊN</div><h2 id="dialogTitle">THỬ LẠI MÀN</h2><p>Đã hết 3 mạng trong phiên thử. Tiến độ học sinh vẫn an toàn.</p><div class="dialog-actions"><button type="button" class="primary-btn" data-action="retry">THỬ LẠI ↗</button><button type="button" class="back-btn" data-action="teacher-return">VỀ GIÁO VIÊN</button></div>',endTeacherTest);return}openDialog('<div class="small-label">HÀNH TRÌNH TẠM DỪNG</div><div class="win-mark">◌</div><h2 id="dialogTitle">HẾT NĂNG LƯỢNG</h2><p>Đã hết 3 mạng ở vùng này. Chơi lại vùng để sửa các lệnh; những vùng đã hoàn thành vẫn được lưu.</p><div class="dialog-actions"><button type="button" class="primary-btn" data-action="retry">THỬ LẠI VÙNG ↗</button><button type="button" class="back-btn" data-action="map">VỀ BẢN ĐỒ</button></div>',()=>setView('map'))}

function openDialog(content,onClose=null,wide=false){stopClock();stopMusic();dialogClose=onClose;$('dialog').classList.toggle('wide',wide);$('dialog').innerHTML=`<button type="button" class="dialog-close" id="dialogX" aria-label="Đóng">×</button>${content}`;$('dialogBackdrop').classList.remove('hidden');$('dialogX').addEventListener('click',closeDialog);$('dialogBackdrop').onclick=e=>{if(e.target===$('dialogBackdrop'))closeDialog()};$('dialog').querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.action;closeDialog(false);if(action==='teacher-return')endTeacherTest();else if(action==='map'){if(teacherTest)endTeacherTest();else setView('map')}else if(action==='retry'){state.index=0;state.lives=3;state.hints=3;state.streak=0;state.freezeUsed=false;state.timeLeft=60;persist();setView('game');renderMission();startMusic();showWarp(state.sector)}}));setTimeout(()=>$('dialog').querySelector('input,button:not(.dialog-close)')?.focus(),0)}
function closeDialog(call=true){const callback=dialogClose;dialogClose=null;$('dialogBackdrop').classList.add('hidden');$('dialog').innerHTML='';if(call&&callback)callback();else if(view==='game'&&state.lives>0&&state.index<missions[state.sector].length){startMusic();resumeClock()}}
function teacherLogin(){openDialog('<div class="small-label">GIÁO VIÊN / MISSION CONTROL</div><h2 id="dialogTitle">BẢNG ĐIỀU KHIỂN</h2><p>Xem cùng bộ 23 nhiệm vụ học sinh gặp và mở đáp án của từng nhiệm vụ.</p><form id="teacherForm"><label class="small-label" for="teacherPass">MẬT KHẨU GIÁO VIÊN</label><input id="teacherPass" class="dialog-input" type="password" autocomplete="off" required placeholder="Nhập mật khẩu"><p id="passwordError" class="dialog-error hidden">Mật khẩu chưa đúng.</p><button class="primary-btn" type="submit">VÀO CHẾ ĐỘ GIÁO VIÊN ↗</button></form><p class="notice">Mã trong website tĩnh chỉ phân chia giao diện; GitHub công khai vẫn cho phép đọc dữ liệu câu hỏi.</p>',()=>{if(view==='game'&&state.lives>0&&state.index<missions[state.sector].length){startMusic();resumeClock()}});$('teacherForm').addEventListener('submit',e=>{e.preventDefault();if($('teacherPass').value===PASSWORD){teacherIndex=0;teacherPanel()}else{$('passwordError').classList.remove('hidden');$('teacherPass').select()}})}
function teacherPanel(){openDialog('<div class="small-label">CHẾ ĐỘ GIÁO VIÊN / BÀI 10</div><h2 id="dialogTitle">23 NHIỆM VỤ BAY</h2><p>5 vùng × 4 nhiệm vụ, cổng cuối × 3. Xem đáp án và chơi thử từng vùng, kể cả vùng chưa mở; không thay đổi tiến độ học sinh.</p><div id="teacherTabs" class="teacher-tabs"></div><button type="button" id="teacherTestBtn" class="primary-btn teacher-test-btn">▶ THỬ MÀN NÀY</button><p class="test-note">Chế độ thử có đủ đồng hồ, gợi ý, 3 mạng và mọi nhiệm vụ trong vùng.</p><div id="teacherGrid" class="teacher-grid"></div><p class="notice">Câu hỏi được viết mới theo nội dung Bài 10 SGK Toán 9, trang 60–62.</p>',()=>{if(view==='game'&&state.lives>0&&state.index<missions[state.sector].length){startMusic();resumeClock()}},true);$('teacherTestBtn').addEventListener('click',()=>beginTeacherTest(teacherIndex));sectors.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.textContent=`${i+1}. ${s.short}`;b.className=i===teacherIndex?'active':'';b.addEventListener('click',()=>{teacherIndex=i;teacherPanel()});$('teacherTabs').append(b)});missions[teacherIndex].forEach(q=>{const c=document.createElement('div');c.className='teacher-card';const answer=q.mode==='input'?nfmt(q.answer):q.mode==='program'?q.order.map((id,i)=>`${i+1}. ${q.pool.find(x=>x.id===id).text}`).join('<br>'):`Dòng ${q.fault+1} → ${q.fixes.find(f=>f.id===q.fix).text}`;c.innerHTML=`<h4>${q.id} · ${q.title.toUpperCase()} · ${q.mode.toUpperCase()}</h4><div class="teacher-math">${q.signal}</div><p>${q.prompt}</p><button class="teacher-reveal" type="button">XEM ĐÁP ÁN</button><div class="teacher-answer"><b>${typesetRoots(answer)}</b><br>${typesetRoots(esc(q.explain))}</div>`;c.querySelector('button').addEventListener('click',()=>{const pane=c.querySelector('.teacher-answer');pane.classList.toggle('open');c.querySelector('button').textContent=pane.classList.contains('open')?'ẨN ĐÁP ÁN':'XEM ĐÁP ÁN'});$('teacherGrid').append(c)})}

$('launchBtn').addEventListener('click',()=>{const raw=$('captainName').value.trim();if(raw)state.name=raw.slice(0,18);persist();sfx.click();setView('map')});$('captainName').value=state.name==='Phi công'?'':state.name;$('captainName').addEventListener('keydown',e=>{if(e.key==='Enter')$('launchBtn').click()});$('homeLogo').addEventListener('click',()=>{if(teacherTest){endTeacherTest();return}if(!$('dialogBackdrop').classList.contains('hidden'))closeDialog(false);setView('home')});$('backBtn').addEventListener('click',()=>{sfx.click();if(teacherTest)endTeacherTest();else setView('map')});$('exitTestBtn').addEventListener('click',endTeacherTest);$('executeBtn').addEventListener('click',execute);$('hintBtn').addEventListener('click',()=>{if(view!=='game'||busy||state.hints<=0)return;const q=missions[state.sector][state.index];state.hints--;persist();updateHud();feedback(q.hint);$('guideLine').textContent='NOVA // Gợi ý định hướng; bạn vẫn cần tự chọn lệnh.';sfx.click()});$('freezeBtn').addEventListener('click',()=>{if(view!=='game'||busy||state.freezeUsed)return;state.freezeUsed=true;freezeUntil=performance.now()+10000;deadline+=10000;persist();updateHud();feedback('Đồng hồ tạm dừng trong 10 giây.');sfx.click()});$('teacherBtn').addEventListener('click',()=>{if(teacherTest)endTeacherTest();else teacherLogin()});$('soundBtn').addEventListener('click',()=>{state.soundOn=!state.soundOn;persist();soundUI();if(state.soundOn){sfx.click();if(view==='game')startMusic()}else stopMusic()});$('volumeBtn').addEventListener('click',()=>{const opening=$('volumePanel').classList.contains('hidden');$('volumePanel').classList.toggle('hidden',!opening);$('volumeBtn').setAttribute('aria-expanded',String(opening))});$('volumeRange').addEventListener('input',e=>{state.volume=Number(e.target.value);if(state.volume>0&&!state.soundOn)state.soundOn=true;persist();soundUI();if(view==='game'){if(state.volume>0&&!music)startMusic();else if(state.volume===0)stopMusic()}});$('volumeRange').addEventListener('change',()=>sfx.click());document.addEventListener('pointerdown',e=>{if(!$('volumeControl').contains(e.target)){$('volumePanel').classList.add('hidden');$('volumeBtn').setAttribute('aria-expanded','false')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('volumePanel').classList.add('hidden');$('volumeBtn').setAttribute('aria-expanded','false')}});soundUI();refreshTeacherTestUI();setView('home');
window.StarcodeDebug={parseNumber,missions};
